website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls, name='admin'),
    path("", include('writers.urls')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

writers/urls.py
from django.urls import path
from . import views

app_name = 'writers'

urlpatterns = [
    path("", views.index, name="index"),
    path("accounts/profile/", views.index, name="profile"),
    path("login/", views.login, name="login"),
    path("authors/", views.authors, name="authors"),
    path("author_detail/<int:id>/", views.author_detail, name="author_detail"),
    path("books/", views.books, name="books"),
    path("books/<int:id>/", views.book_detail, name="book_detail"),
    path("team/", views.team, name="team"),
    path("poems/", views.poems, name="poems"),
    path("poems/<int:id>/", views.poem_detail,name="poem_detail"),
    path("poems_save/<int:id>/", views.save_poems,name="save_poems"),
    path("poems_unsave/<int:id>/", views.unsave_poems,name="unsave_poems"),
    path("poems_saved/", views.poems_saved, name="poems_saved"),
]

writers/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    name = models.CharField(max_length=90)
    image = models.ImageField(upload_to='author/cover/%Y/%m/%d/', blank=True, default="")
    bio = models.CharField(max_length=300)
    death = models.CharField(max_length=300)
    date_birth = models.DateField(blank=False)
    date_death = models.DateField(blank=True, default=None)
    is_dead = models.BooleanField(default=False)
    is_poem_author = models.BooleanField(default=False)
    is_book_author = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)
    
    
    def __str__(self):
        return self.name
    
    
class Book(models.Model):
    title = models.CharField(max_length=100)
    number_of_pages = models.PositiveIntegerField(default=0)
    synopsis = models.TextField(default='')
    download = models.URLField()
    image = models.ImageField(upload_to='books/cover/%Y/%m/%d/')
    is_published = models.BooleanField(default=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title
    
class Poem(models.Model):
    title = models.CharField(max_length=100)
    mini_description = models.TextField(max_length=255)
    text = models.TextField(max_length=4000)
    is_published = models.BooleanField(default=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='saved_poems', blank=True)
    saved = models.BooleanField(default=False)

    def save(self, user):
        if user not in self.users.all():
            self.users.add(user)
            self.saved = True 
            
        else:
            self.users.remove(user)
            self.saved = False
        super().save()

        
    def unsave(self, user):
        self.users.remove(user)
        self.saved = False
        super().save()
    

    def __str__(self):
        return self.title

writers/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Author, Book, Poem
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.db.models import Q
from django.core.paginator import Paginator

def index(request):
    return render(request, 'writers/index.html', {'page_title': 'Writers!'})


def login(request):
    return render(request, 'writers/login.html', {'page_title': 'Login!'})



def authors(request):
    page_title = 'Authors!'
    authors = Author.objects.all().filter(is_published=True, is_dead=True, is_poem_author=True)
    if request.method == "POST":
        search = request.POST.get('home-searchbar')
        if len(search) > 0:    
            authors = Author.objects.all().filter(
                Q(name__icontains=search) |
                Q(death__icontains=search) | 
                Q(bio__icontains=search), is_published=True, is_dead=True, is_poem_author=True)
    
    paginator = Paginator(authors, 15)
    page_number = request.GET.get("page")
    authors = paginator.get_page(page_number)

    return render(request, 'writers/authors.html', {'page_title': page_title,'authors': authors,})

def author_detail(request, id):
    author = Author.objects.get(id=id)
    poems_by_author = Poem.objects.filter(author=author)[:3]
    return render(request, 'writers/partials/author_detail.html', {'author': author,'poems_by_author': poems_by_author})

def books(request):
    books = Book.objects.all()
    paginator = Paginator(books, 8)
    page_number = request.GET.get("page")
    books = paginator.get_page(page_number)
    return render(request, 'writers/books.html', {'page_title': 'Book!','books':books,})

def team(request):
    return render(request, 'writers/team.html', {'page_title': 'Team!',})


def book_detail(request, id):
    book = get_object_or_404(
        Book,
        id=id,
    )
    return render(request, 'writers/book_detail.html', 
    {'page_title': book.title.title() + ' - Writers',
     'book': book,
     })

def poems(request):
    last_poem = Poem.objects.last()
    poem = Poem.objects.all().exclude(id=last_poem.id)
    return render(request, 'writers/poems.html', {'page_title': 'Poems!',
     'poems': poem,
     'last_poem': last_poem,
     })
    
    
    

def poem_detail(request, id): 
    poem = get_object_or_404(
        Poem,
        id=id,
    )
    
    saved = False
    if poem.users.filter(id=request.user.id).exists():
        saved = True
    else:
        saved = False
    
    return render(request, 'writers/poem.html', 
    {'page_title': poem.title,
     'poem': poem,
     'saved': saved,
     })
    
@login_required(login_url=reverse_lazy('account_login'))
def save_poems(request, id):
    poem = get_object_or_404(Poem, id=id)
    poem.save(request.user)
    
    return redirect('writers:poems')

@login_required(login_url=reverse_lazy('account_login'))
def unsave_poems(request, id):
    poem = get_object_or_404(Poem, id=id)
    poem.unsave(request.user)
    
    return redirect('writers:poems')

@login_required(login_url=reverse_lazy('account_login'))
def poems_saved(request):
    poems = Poem.objects.filter(users=request.user)

    return render(request, 'writers/saved.html',{
        'page_title': "Favoritos",
        'poems': poems,
        'is_saved': True,
    })

writers/templates/writers/authors.html
{% include 'writers/partials/head.html' %}
<body>
    <main class="main">
       {% include 'writers/partials/header.html' %}
        <form class="home-search" action="{% url "writers:authors" %}" method="POST">
            {% csrf_token %}
            <input type="search" name="home-searchbar" id="home-searchbar" placeholder="PESQUISAR">
        </form>
            <div class="main-home">
                <div class="home-menu d-block">
                    {% for author in authors %}
                        <div class="home-menu-itens-authors">
                                <div class="itens-img-authors">
                                    {% if author.image %}
                                        <img src="{{author.image.url}}">
                                    {% endif %}
                                </div>
                                <div class="itens-info">                   
                                    <h2 class="itens-author-name">{{author.name}}</h2>
                                    <p class="itens-author-death">{{author.date_birth}}</p>
                                    <a href="{% url 'writers:author_detail' author.id %}" class="itens-more">Saiba mais sobre o poeta {{author.name}}</a>
                                </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="page-navigation">
                    <div>
                    <span class="current">
                        Página {{ authors.number }} de {{ authors.paginator.num_pages }}.
                    </span>
                    <div class="pagination-button">
                    {% if authors.has_previous %}
                        <a href="?page=1">Primeira Página</a>
                        <a href="?page={{ authors.previous_page_number }}">&le; Anterior</a>
                    {% endif %}
                       
                    {% if authors.has_next %}
                        <a class="pagination-next" href="?page={{ authors.next_page_number }}"> Próximo &ge;</a>
                        <a class="pagination-back" href="?page={{ authors.paginator.num_pages }}">Ultima Página</a>
                    {% endif %}                 
                </div>
            </div>       
    </main>
    {% include 'writers/partials/footer.html' %}
</body>
</html>

writers/templates/writers/book_detail.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'writers/partials/head.html' %}
</head>
<body>
    {% include 'writers/partials/header.html' %}
    <section class="book">
        <div class="book-info">
            <div class="book-img">
                <img src="{{book.image.url}}" alt="book-img">
            </div>
            <div class="book-text-info">
                <h1><b>Título:</b> {{book.title|title}}</h1>
                <h1><b>Autor:</b> {{book.author.name}}</h1>
                <h1><b>N° de Páginas:</b> {{book.number_of_pages}}</h1>
                <h1><b>Tipo:</b> Livro Digital</h1>
                <h1><b>Formato:</b> Pdf</h1>
            </div>
        </div>
        <div class="book-info2">
            <div class="book-synopsis">
                <p>{{book.synopsis}}</p>
            </div>
            <a class="book-link" href="{{book.download}}" target="_blank">
                <img src="{% static "writers/images/download-button.svg" %}" alt="download">
            </a>
        </div>
        
    </section>
</body>
</html>

writers/templates/writers/books.html
{% load static %}
{% include 'writers/partials/head.html' %}
<body>
    {% include 'writers/partials/header.html' %}
        <div class="main-author">
            <h2>Livros</h2>
        </div>
            <div class="main-home">
                <div class="home-menu-book">
                    {% for book in books %}
                        <a href="{% url 'writers:book_detail' book.id %}" class="home-menu-itens-book">
                            <div class="itens-img-book">
                                <img src="{{book.image.url}}" alt="books-img">
                            </div>
                            <div class="itens-text-book">
                                <h1><strong>{{book.title}}</strong></h1>
                                <h2><strong>AUTHOR(A):</strong>{{book.author}}</h2>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="page-navigation">
                <div>
                <span class="current">
                    Página {{ books.number }} de {{ books.paginator.num_pages }}.
                </span>
                <div class="pagination-button">
                    {% if books.has_previous %}
                        <a href="?page=1">Primeira Página</a>
                        <a href="?page={{ books.previous_page_number }}">&le; Anterior</a>
                    {% endif %}
                    
                    {% if books.has_next %}
                        <a class="pagination-next" href="?page={{ books.next_page_number }}"> Próximo &ge;</a>
                        <a class="pagination-back" href="?page={{ books.paginator.num_pages }}">Ultima Página</a>
                    {% endif %}    
                </div>             
            </div>
        </div>
    </main>
    {% include 'writers/partials/footer.html' %}
</body>

</html>

writers/templates/writers/index.html
{% load static %}
{% include 'writers/partials/head.html' %}
<body>
    <main class="main">
        {% include 'writers/partials/header.html' %}
        <form class="home-search" action="">
            <input type="search" name="home-searchbar" id="home-searchbar" placeholder="PESQUISAR">
        </form>
        <div class="main-home">
            <div class="home-menu">
                <a href="{% url 'writers:books' %}" class="home-menu-itens">
                    <div  class="itens-img">
                        <img src="{% static 'writers/images/books-img.png' %}" alt="books-img">
                    </div>
                    <p class="itens-text">
                        LIVROS
                    </p>
                </a>
                <a href="{% url 'writers:poems' %}" class="home-menu-itens">
                    <div class="itens-img">
                        <img src="{% static 'writers/images/poems-img.png' %}" alt="poems-img">
                    </div>
                    <p class="itens-text">
                        POEMAS
                    </p>
                </a>
                <a href="{% url 'writers:authors' %}" class="home-menu-itens">
                    <div class="itens-img">
                        <img src="{% static 'writers/images/authors-img2.png' %}" alt="authors-img">
                    </div>
                    <p class="itens-text">
                        AUTORES
                    </p>
                </a>
                <a href="{% url "writers:poems_saved" %}" class="home-menu-itens">
                    <div class="itens-img">
                        <img src="{% static 'writers/images/favorite.svg' %}" alt="authors-img">
                    </div>
                    <p class="itens-text">
                        FAVORITOS
                    </p>
                </a>
            </div>
        </div>
    </main>
    {% include 'writers/partials/footer.html' %}
   
</body>
</html>

writers/templates/writers/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Writers.blog</title>
    <link rel="stylesheet" href="../templates/css/styles.css">
    <script src="../templates/js/main.js"></script>
</head>
<body class="login">
    <main class="main-login">
        <header>
            <a onclick="main()" class="header-left">
                <div  class="header-logo">
                    <img src="../templates/images/header-logo.png" alt="header-logo">
                </div>
                <h1 class="header-text">
                    WRITERS
                </h1>
            </a>
            <a href="" class="header-profile-img">
                <img src="../templates/images/profile-img.png" alt="profile-img">
            </a>
        </header>
        <div class="main-home-login">
            <div class="home-menu-login">
                <div class="login-container">
                    <div class="login-text">
                        <h1>Writers.blog</h1>
                        <p>Login</p>
                    </div>
                    <div class="input-wrapper">
                    <label for="nome">NOME:</label>
                    <input type="text" id="nome">
                    </div>
                    <div class="input-wrapper">
                    <label for="email">EMAIL:</label>
                    <input type="email" id="email">
                    </div>
                    <div class="input-wrapper">
                    <label for="senha">SENHA:</label>
                    <input type="password" id="senha">
                    </div>
                    <button class="login-button">Fazer Login</button>
                </div>   
            </div>           
        </div>
    </main>
</body>
</html>

writers/templates/writers/partials/author/CarlosDrummondDeAndrade.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Writers.blog</title>
    <link rel="stylesheet" href="../../templates/css/styles.css">
    <script src="../../templates/js/main.js"></script>
</head>
<body>
    <main class="main">
        <header>
            <a onclick="main()" class="header-left">
                <div  class="header-logo">
                    <img src="../../templates/images/header-logo.png" alt="header-logo">
                </div>
                <h1 class="header-text">
                    WRITERS
                </h1>
            </a>
            <a href="../login.html" class="header-profile-img">
                <img src="../../templates/images/profile-img.png" alt="profile-img">
            </a>
        </header>
        <div class="main-author">
            <h2>Carlos Dummond de Andrade</h2>
        </div>
            <div class="main-home-author">
                <div class="home-menu-authors'">
                    <div class="menu-authors">
                        <div class="info">
                            <div class="itens-info-about">                   
                                <h3 class="itens-author-who">Quem foi Calos Drummond de Andrade?</h3>
                                <p class="itens-author-about">Carlos Drummond de Andrade foi um poete, farmacêutico, contista e cronista brasileiro, considerado por muitos o mais influente poeta brasileiro do século XX.</p>
                            </div>
                            <div class="itens-info-death">                   
                                <h3 class="itens-author-who">Morte</h3>
                                <p class="itens-author-about">Morreu no dia 17 de agosto de 1987, no Rio de Janeiro, aos 84 anos, apenas 12 dias depois da morte de sua única filha Maria Julieta Drummond de Andrade.</p>
                            </div>
                        </div>
                        
                       <div class="poems">
                            
                            <div class="main-poems">
                                <h3>Poemas</h3>
                                <ul>
                                    <li>Congresso Internacional do Medo</li>
                                    <li>Assnhamento</li>
                                    <li>Sentimental</li>
                                </ul>
                            </div>
                            <div class="itens-img-authors">
                                <img src="../../templates/images/authors/carlos_drummond_de_andrade.jpg" alt="books-img">
                            </div>
                       </div>
                    </div>
                </div>
            </div>       
    </main>
</body>
</html>

writers/templates/writers/partials/author_detail.html
{% load static %}
{% include 'writers/partials/head.html' %}
<body>
    <main class="main">
        {% include 'writers/partials/header.html' %}
        <div class="main-author">
            <h2>{{author.name}}</h2>
        </div>
            <div class="main-home-author">
                <div class="home-menu-authors'">
                    <div class="menu-authors">
                        <div class="info">
                            <div class="itens-info-about">                   
                                <h3 class="itens-author-who">Quem foi {{author.name}}?</h3>
                                <p class="itens-author-about">{{author.bio}}</p>
                            </div>
                            <div class="itens-info-death">                   
                                <h3 class="itens-author-who">Morte</h3>
                                <p class="itens-author-about">{{author.death}}</p>
                            </div>
                        </div>
                        
                       <div class="poems">
                        {% if poems_by_author %}
                            <div class="main-poems">
                                <h3>Poemas</h3>
                                <ul>
                                    {% for poem in poems_by_author %} 
                                    <li>
                                        <a class="text-decoration-none" href="{% url "writers:poem_detail" poem.id %}">{{poem.title}}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                            <div class="itens-img-authors">
                                {% if author.image %}
                                <img src="{{author.image.url}}">
                                {% endif %}                            </div>
                       </div>
                    </div>
                </div>
            </div>       
    </main>
</body>
</html>

writers/templates/writers/partials/footer.html
{% load static %}
{% load i18n %}

<footer>
    <div class="footer-area">
        <div class="footer-logo">
            <div class="header-logo">
                <img src="{% static 'writers/images/header-logo.png' %}" alt="header-logo">
            </div>
            <h1 class="header-text">
                WRITERS
            </h1>
        </div>
        <div class="footer-text">
            <h1>Colecione e compartilhe frases de poemas e livros</h1>
        </div>
        <div class="footer-menu">
            <a href="{% url 'writers:index' %}" class="footer-menu-item">
                <h1>Inicio</h1>
            </a>
            <a href="{% url 'writers:books' %}" class="footer-menu-item">
                <h1>Livros</h1>
            </a>
            <a href="{% url 'writers:index' %}" class="footer-menu-item">
                <h1>Poemas</h1>
            </a>
            <a href="{% url 'writers:authors' %}" class="footer-menu-item">
                <h1>Autores</h1>
            </a>
            <a href="{% url 'writers:poems_saved' %}" class="footer-menu-item">
                <h1>Favoritos</h1>
            </a>
        </div>
        <h1 class="footer-copyright">©2023</h1>
    </div>
</footer>

writers/templates/writers/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ page_title }}</title>
    <link rel="shortcut icon" href="{% static 'writers/images/header-logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'writers/css/styles.css' %}">
</head>

writers/templates/writers/partials/header.html
{% load static %}
<script src="{% static 'writers/js/sidebar.js' %}"></script>
{% include 'writers/partials/sidebar.html' %}
<header>
    <a href="{% url 'writers:index' %}" class="header-left">
        <div class="header-logo">
            <img src="{% static 'writers/images/header-logo.png' %}" alt="header-logo">
        </div>
        <h1 class="header-text">
            WRITERS
        </h1>
    </a>
    <div class="header-profile-img">
        <img src="{% static 'writers/images/profile-img.png' %}" alt="menu-btn" id="home-linkstyle-menu" onclick="entrar()">
    </div>
</header>

writers/templates/writers/partials/sidebar.html
{% load static %}
{% load i18n %}
<div id="sidebar-off" onclick="sair()"></div>

<div id="sidebar">
    <div class="sidebar-user">
        <div class="user-img">
            {% if user.is_authenticated and user.image  %}
            <img src="" alt="">
            {% else %}
            <img src="{% static 'writers/images/default_user_img.png' %}" alt="">
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <h3 class="user-name">{{ user.username|title }}</h3>
        {% else %}
        <h3 class="user-name">{% trans "Usuário não cadastrado!" %}</h3>
        {% endif %}
        
    </div>
    {% if user.is_authenticated %}
        <a class="sidebar-block" href=""> {% trans "PERFIL" %}</a>
        <a class="sidebar-block sidebar-block-bottom" href="{% url 'account_logout'  %}">{% trans "SAIR" %}</a>
    {% else %}
        <a class="sidebar-block" href="{% url 'account_login'  %}">{% trans "ENTRAR" %}</a>
        <a class="sidebar-block" href="{% url 'account_signup'  %}">{% trans "REGISTRAR" %}</a>
        
    {% endif %}
    <h3>Site</h3>
    <div class="sidebar-site-options block-options">
        <a class="sidebar-block sidebar-site-option" href="{% url 'writers:books'  %}">{% trans "LIVROS" %}</a>
        <a class="sidebar-block sidebar-site-option" href="{% url 'writers:poems'  %}">{% trans "POEMAS" %}</a>
        <a class="sidebar-block sidebar-site-option" href="{% url 'writers:authors'  %}">{% trans "AUTORES" %}</a>

        <a class="sidebar-block sidebar-site-option" href="{% url "writers:poems_saved" %}">{% trans "FAVORITOS" %}</a>
        <a class="sidebar-block sidebar-site-option" href="{% url 'writers:team'  %}">{% trans "QUEM SOMOS" %}</a>
    </div>
</div>
    
    
    

writers/templates/writers/poem.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sessão Poema</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'writers/css/poem.css' %}">
</head>

{% include 'writers/partials/head.html' %}
<body>
    
    {% include 'writers/partials/header.html' %}
    
    
    <div class="container mt-4 poem-size">
        <div class=" ">
            <div class="col-lg-5 me-lg-7 poem-size-100">
                <a href="{% url "writers:poems" %}" class="session-poem-bg anti-link">Voltar</a>
                <div class="session-poem-bg">Sessão Poema</div>

                {% if saved %}
                <a href="{% url "writers:unsave_poems" poem.id %}" class="session-poem-bg anti-link">Desfavoritar</a>
                {% else %}
                <a href="{% url "writers:save_poems" poem.id %}" class="session-poem-bg anti-link">Favoritar</a>
                {% endif %}
                

            

                <div class="poem-title">{{poem.title}} - {{poem.author.name}}</div>

                <div class="poem-text">
                    {{poem.text|linebreaksbr}}
                </div>
                
            </div>
    
            <!-- Lado direito: Imagem -->
            <div class="author-img"> <!-- Margem superior adicionada para dispositivos móveis -->
                {% if poem.author.image %}
                <img src="{{poem.author.image.url}}" alt="Imagem descritiva" class="img-fluid">
                {% endif %}
            </div>
        </div>
    </div>
    

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

writers/templates/writers/poems.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poemas</title>
</head>
{% include 'writers/partials/head.html' %}
<body>
    {% include 'writers/partials/header.html' %}
    <section class="poems-list">
        <div class="last">      
            <h2 class="last-main-text">DESTAQUES</h2>
            <div class="last-poem">
                <div class="last-poem-title">
                    <h1>{{last_poem.title}} - {{last_poem.author.name}}</h1>
                </div>
                <div class="last-poem-content">
                    <h2>{{ last_poem.mini_description|linebreaksbr }}</h2>
                    <div class="poem-detail">
                        <a href="{% url 'writers:poem_detail' last_poem.id %}">Ler mais</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="other-poems">
            <h2 class="last-main-text">Outros Poemas</h2>
            {% for poem in poems %}
            <div class="last-poem">
                <div class="last-poem-title">
                    <h1>{{poem.title}}</h1>
                </div>
                <div class="last-poem-content">
                    <h2>{{ poem.mini_description|linebreaksbr }}</h2>
                    <div class="poem-detail">
                        <a href="{% url 'writers:poem_detail' poem.id %}">Ler mais</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </section>
</body>
</html>

writers/templates/writers/saved.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Poemas</title>
</head>
{% include 'writers/partials/head.html' %}
<body>
    {% include 'writers/partials/header.html' %}
    <section class="poems-list">
        <div class="other-poems">
            <h2 class="last-main-text">Poemas Favoritos</h2>
            {% for poem in poems %}
            <div class="last-poem">
                <div class="last-poem-title">
                    <h1>{{poem.title}}</h1>
                </div>
                <div class="last-poem-content">
                    <h2>{{ poem.mini_description|linebreaksbr }}</h2>
                    <div class="poem-detail">
                        <a href="{% url 'writers:poem_detail' poem.id %}">Ler mais</a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="last-poem">
                <div class="last-poem-title">
                    <h1>Você ainda não tem poemas salvos</h1>
                </div>
            </div>
            {% endfor %}
        </div>

    </section>

    
</body>
</html>